receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp:
    endpoint: "${env:EXPORT_URL}"
    headers:
      Authorization: "${env:AUTH_HEADER}"
      X-P-Log-Source: otel
      X-P-Stream: "${env:STREAM_NAME}"
      Content-Type: application/json
    tls:
      insecure: true
    encoding: json

  debug:
    verbosity: detailed

  nop:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [otlphttp]

    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ nop ]

    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ nop ]