networks:
  default:
    name: dev
    external: false

volumes:
  prometheus_data:
    driver: local

services:
  demo:
    build:
      context: ../demo
    container_name: demo_app_prometheus
    hostname: demo_app
    environment:
      - OTEL_EXPORTER_OTEL_URL=http://collector:4317
      - OTEL_EXPORT_PROTOCOL=grpc
      - RUST_LOG=info
      - METRICS_EXPORT=http://prometheus:9201/write
    ports:
      - "5000:5000"

  collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel_collector_prometheus
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports: # I expose all possible ports for demo app
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension


  prometheus:
    image: prom/prometheus
    container_name: prometheus_demo
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
      - "9201:9201"
#    command:
#      - "--enable-feature=otlp-write-receiver"


  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"