receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  nop:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [nop]

    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ nop ]

    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ nop  ]