receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp:
    endpoint: "${env:EXPORT_URL}"
    headers:
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"
    tls:
      insecure: true
#      cert_file: /usr/share/certs/fleet-server/fleet-server.crt
#      key_file: /usr/share/certs/fleet-server/fleet-server.key

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [otlp]